delete from Addin_MDS_Province
delete from Addin_MDS_ProvinceHCDRel

DBCC CHECKIDENT (Addin_MDS_Province, reseed, 0)
DBCC CHECKIDENT (Addin_MDS_ProvinceHCDRel, reseed, 0)

INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (4, 'ALMERÍA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (11, 'CÁDIZ', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (14, 'CÓRDOBA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (18, 'GRANADA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (21, 'HUELVA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (23, 'JAÉN', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (29, 'MÁLAGA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (41, 'SEVILLA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (22, 'HUESCA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (44, 'TERUEL', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (50, 'ZARAGOZA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (33, 'ASTURIAS', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (7, 'BALEARES', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (8, 'BARCELONA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (17, 'GIRONA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (25, 'LLEIDA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (43, 'TARRAGONA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (39, 'CANTABRIA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (51, 'CEUTA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (5, 'ÁVILA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (9, 'BURGOS', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (24, 'LEÓN', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (34, 'PALENCIA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (37, 'SALAMANCA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (40, 'SEGOVIA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (42, 'SORIA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (47, 'VALLADOLID', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (49, 'ZAMORA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (2, 'ALBACETE', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (13, 'CIUDAD REAL', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (16, 'CUENCA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (19, 'GUADALAJARA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (45, 'TOLEDO', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (35, 'LAS PALMAS DE GRAN CANARIA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (38, 'SANTA CRUZ DE TENERIFE', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (3, 'ALACANT/ALICANTE', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (12, 'CASTELLÓ DE LA PLANA/CASTELLÓN', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (46, 'VALENCIA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (6, 'BADAJOZ', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (10, 'CÁCERES', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (15, 'CORUÑA, A', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (27, 'LUGO', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (32, 'OURENSE', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (36, 'PONTEVEDRA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (28, 'MADRID', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (52, 'MELILLA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (30, 'MURCIA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (31, 'NAVARRA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (1, 'ARABA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (20, 'GIPUZKOA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (48, 'BIZKAIA', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_Province (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (26, 'LA RIOJA', 1, GetDate(), 'ACT_CMBD')


INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (1, 62, 'ALMERÍA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (2, 63, 'CÁDIZ', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (3, 64, 'CÓRDOBA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (4, 65, 'GRANADA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (5, 66, 'HUELVA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (6, 67, 'JAÉN', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (7, 68, 'MÁLAGA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (8, 69, 'SEVILLA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (9, 70, 'HUESCA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (10, 71, 'TERUEL', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (11, 72, 'ZARAGOZA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (12, 73, 'ASTURIAS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (13, 74, 'BALEARES', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (14, 75, 'BARCELONA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (15, 76, 'GIRONA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (16, 77, 'LLEIDA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (17, 78, 'TARRAGONA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (18, 79, 'CANTABRIA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (19, 80, 'CEUTA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (20, 81, 'ÁVILA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (21, 82, 'BURGOS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (22, 83, 'LEÓN', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (23, 84, 'PALENCIA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (24, 85, 'SALAMANCA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (25, 86, 'SEGOVIA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (26, 87, 'SORIA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (27, 88, 'VALLADOLID', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (28, 89, 'ZAMORA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (29, 90, 'ALBACETE', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (30, 91, 'CIUDAD REAL', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (31, 92, 'CUENCA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (32, 93, 'GUADALAJARA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (33, 94, 'TOLEDO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (34, 95, 'LAS PALMAS DE GRAN CANARIA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (35, 96, 'SANTA CRUZ DE TENERIFE', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (36, 97, 'ALACANT/ALICANTE', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (37, 98, 'CASTELLÓ DE LA PLANA/CASTELLÓN', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (38, 99, 'VALENCIA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (39, 100, 'BADAJOZ', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (40, 101, 'CÁCERES', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (41, 102, 'CORUÑA, A', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (42, 103, 'LUGO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (43, 104, 'OURENSE', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (44, 105, 'PONTEVEDRA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (45, 106, 'MADRID', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (46, 107, 'MELILLA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (47, 108, 'MURCIA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (48, 109, 'NAVARRA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (49, 110, 'ARABA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (50, 111, 'GIPUZKOA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (51, 112, 'BIZKAIA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_ProvinceHCDRel (MDSProvinceID, ProvinceID, ProvinceName, LastUpdated, ModifiedBy) VALUES (52, 113, 'LA RIOJA', GetDate(), 'ACT_CMBD')
