Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (42,'DESAYUNO-CENA (09-20)','DESAYUNO-CENA (09:00 Y  20:00)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (43,'DE-CO-ME-CE','DE-CO-ME-CE',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (50,'DESAYUNO-MERIENDA (09-17)','DESAYUNO-MERIENDA (09:00 Y 17:00)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (51,'DESAYUNO-MERIENDA-23','DESAYUNO-MERIENDA-23:00',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (52,'12H (04 - 16)','12H (04 - 16)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (55,'04H (04-08-12-16-20-24)','04H (04-08-12-16-20-24)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (77,'06H (06-12-18-24)','06H (06-12-18-24)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (81,'LIBRE','LIBRE',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (82,'AHORA','AHORA',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (41,'DESAYUNO (08)','EN EL DESAYUNO DESAYUNO (08:00)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (56,'06H A (03-09-15-21)','06H A (03-09-15-21)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (216,'05 VECES DIA (0-05-10-15-20)','05 VECES DIA (0-05-10-15-20)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (73,'03H (03-06-09-12-...)','03H (03-06-09-12-...)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (53,'02H (02-04-06-08-...)','02H (02-04-06-08-...)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (37,'72H','72H',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (79,'08H (08-16-24)','08H (08-16-24)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (45,'DESAYUNO-COMIDA (09-13)','DESAYUNO-COMIDA (09:00 Y  13:00)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (101,'A LAS 8 Y 16','A LAS 08 Y 16 HORAS',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (102,'A LAS 8, 16 Y 23','A LAS 8:00, 16:00 Y 23:00',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (70,'12H (06 - 18)','12H (06 - 18)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (103,'12H (12 - 24)','12H (12 - 24)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (104,'12H A (08 - 20)','12H A (08 - 20)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (105,'24H (09)','24H (09)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (111,'24H (23)','24H (23)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (57,'08H A (04-12-20)','08H A (04-12-20)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (46,'DES-COM-CENA (08-13-20)','DES-COM-CENA (08:00-13:00-20:00)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (121,'DESAYUNO-COMIDA-CENA-23','DESAYUNO-COMIDA-CENA-23:00',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (14,'CENA (20)','EN LA CENA (20:00)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (16,'COMIDA (13)','EN LA COMIDA (13:00)',1,getdate(),'CargaInicial')
Insert into IB_IMQ_FrecuenciasEfarmaco (ID,Name,Definition, Status, LastUpdated, ModifiedBy) values (32,'48H','48H',1,getdate(),'CargaInicial')


