UPDATE PhysicalUnit SET Name='MCG'where Mnemonic ='GM'
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('APLIC', 'APLICACION', 'APLICACION', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('CAP', 'CAPSULAS', 'CAPSULAS', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('COMP', 'COMPRIMIDOS', 'COMPRIMIDOS', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('DOSIS', 'DOSIS', 'DOSIS', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('GOTAS', 'GOTAS', 'GOTAS', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('G.', 'GRAMOS', 'GRAMOS', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('INH', 'INHALACION', 'INHALACION', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('JER', 'JERINGA', 'JERINGA', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('MCG', 'MICROGRAMOS', 'MICROGRAMOS', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('MG.', 'MILIGRAMOS', 'MILIGRAMOS', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('ML.', 'MILILITROS', 'MILILITROS', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('NEBULIZACION', 'NEBULIZACION', 'NEBULIZACION', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('U.', 'UNIDADES', 'UNIDADES', 0, 8, 1, 0, 1, GETDATE(), '44681293')
insert into PhysicalUnit (Mnemonic, Definition, Name, ConversionImpliesID, UnitType, InUse, IsDefault, Status, LastUpdated, ModifiedBy)
values ('UI.', 'UNIDADES INTERNACIONALES', 'UNIDADES INTERNACIONALES', 0, 8, 1, 0, 1, GETDATE(), '44681293')