delete from Addin_MDS_FinancingType
delete from Addin_MDS_FinancingTypeHCDRel

DBCC CHECKIDENT (Addin_MDS_FinancingType, reseed, 0)
DBCC CHECKIDENT (Addin_MDS_FinancingTypeHCDRel, reseed, 0)

INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (1, 'Sistema Nacional de Salud (SNS)', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (2, 'Reglamentos europeos y convenios bilaterales', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (3, 'Mutualidades de funcionarios del estado y otras AAPP', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (4, 'Accidentes laborales y enfermedades profesionales. Mutuas colaboradoras con la Seguridad Social', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (5, 'Accidentes de tráfico', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (6, 'Financiación privada directa (Personas físicas)', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (7, 'Financiación mediante seguro privado', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (8, 'Asistencia sanitaria transfronteriza', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (11, 'Instituciones  penitenciarias', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (12, 'Accidente escolar', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (13, 'Accidente deportivo', 1, GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingType (Code, Name, Status, LastUpdated, ModifiedBy) VALUES (19, 'Otros y Desconocido', 1, GetDate(), 'ACT_CMBD')


INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 149, 'A.B.S.V.S', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 122, 'ACADEMIA POLICIA PAIS VASCO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 144, 'ACTIVA MUTUA 2008', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 133, 'ADIF', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 95, 'AEGON', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 193, 'AIG EUROPE', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 214, 'AIG EUROPE LIMITED/ CS24 S.L', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 129, 'ALLIANZ', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 184, 'AMA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 194, 'AMDIF', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 125, 'AMIC', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 201, 'ARAG S.E SUCURSAL ESPAÑA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 97, 'ARESA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 156, 'ASEFA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 213, 'ASEGURADORAS VARIAS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 117, 'ASEPEYO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 202, 'ASESORAMIENTO MEDICO SIGLO XXI', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 109, 'ASISA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 154, 'ATLANTIS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 111, 'AXA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 110, 'AXA WINTERTHUR', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 124, 'AZUR MULTIRRAMOS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 171, 'BALUMBA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 196, 'BARGAIZ 1951 S.L.', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 215, 'BIZI KALITATEA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 164, 'CABLES Y ALAMBRES ESPECIALES', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 189, 'CAHISPA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 105, 'CASER', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 177, 'CATALANA OCCIDENTE', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 211, 'CELTA ASSITANCE SL', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 198, 'CEMEDESA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 199, 'CEMEDESA SERVICIOS MEDICOS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 113, 'CENTRO INTERMUTUAL DE EUSKADI', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 147, 'CENTRO OTORRRINOLARINGOLOGICO BILBAINO S', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 103, 'CIGNA SALUD', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 138, 'CISNE ASEGURADORA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 165, 'CLICKSEGUROS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 163, 'CONSORCIO COMPENSACION DE SEGUROS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 172, 'CORIS ASISTENCIA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 56, 'CVSS-CVB UTE  LEY 18/1982', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 137, 'DIRECCION PROVINCIAL.DE LA TGSS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 116, 'DKV', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 104, 'EGARSAT MATEPSS N 276', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 119, 'EL OCASO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 195, 'ETERNA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 187, 'EURO INSURANCE LIMITED', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 153, 'EUROMUTUA SEGUROS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 170, 'FENIX DIRECTO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 96, 'FIATC', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 204, 'FIDELIDADE MUNDIAL', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 169, 'FRATERNIDAD-MUPRESPA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 99, 'FREMAP', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 107, 'GENERALI', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 123, 'GENESIS AUTO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 134, 'GES', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 150, 'GESMEDIC 2012', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 126, 'GESTION INTEGRAL OFTALMOLOGICA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 206, 'GOBIERNO VASCO DTO INTERIOR', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 106, 'HELVETIA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 151, 'HEMOBESA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 205, 'HEMODINAMICA VIZCAYA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 178, 'HILO DIRECT', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 216, 'HNA SERVIC.CORPORATIVOS SEGUROS Y PENSIO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 200, 'I.N.S.S. SEGUROS ESCOLAR', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 140, 'IBERO ASISTENCIA S.A', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 209, 'IMA IBERICA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 92, 'IMQ', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 183, 'INEAS INTERNACIONAL INSURANC. CORPORATIO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 212, 'INIVI CENTRO MEDICO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 136, 'INSTITUTO SOCIAL DE LA MARINA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 173, 'INSUTEK', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 168, 'LA PATRIA HISPANA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 93, 'LAGUN ARO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 160, 'LE MANS SEGUROS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 152, 'LIBERTY SEGUROS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 158, 'LINEA DIRECTA ', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 157, 'MAAF SEGUROS CIA ESPAÑO.DE SEG.Y REA. SA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 127, 'MAPFRE ESPAÑA CIA SEGUROS Y REASEGUROS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 112, 'MAPFRE VIDA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 217, 'MARKELT INTERNANTIONAL ESPAÑA/CS24 S.L', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 146, 'MARVIC 2010', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 218, 'MEDICAL CARE SOUTH, S.L.', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 203, 'MEDICAL DISCOUNT', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 185, 'MEDICAL PREVENCION XXI', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 181, 'METROPOLIS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 128, 'MGS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 207, 'MM GLOBALIS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 162, 'MONDIAL ASSIST', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 176, 'MURIMAR', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 219, 'MUSSAP', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 143, 'MUTUA BALEAR', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 190, 'MUTUA FLEQUERA DE CATALUÑA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 188, 'MUTUA INTERCOMARCAL', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 145, 'MUTUA MADRILEÑA AUTOMOVILISTA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 197, 'MUTUA MADRILEÑA DEL TAXI', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 94, 'MUTUA UNIVERSAL N 10', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 161, 'MUTUA VALENCIANA AUTO DE SEGUROS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 220, 'MUTUADAD.PREVI.SOCIAL FUTBOLISTAS ESPAÑO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 130, 'MUTUAL MIDAT CYCLOPS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 100, 'MUTUALIA MUTUA DE ACC.DE TRAB Y ENF.PROF', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 101, 'MUTUALIDAD G.P.H DIVINA PASTORA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 179, 'NACIONAL SUIZA CIA ESPAÑOLA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 182, 'NATIONAL NEDERLANDER', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (1, 135, 'OSAKIDETZA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 159, 'PELAYO MUTUA DE SEGUROS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 132, 'PLUS ULTRA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 70, 'PLUS ULTRA 1', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 208, 'PRESTIMA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (6, 90, 'PRIVADO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 191, 'PROSPERTY', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 166, 'RACC', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 221, 'RACC SERVEIS MEDICS SA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 180, 'REALE UNION ASEGURADORA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 121, 'RENFE', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 167, 'S.U.R.N.E.', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 114, 'SANITAS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 192, 'SEGUR CAIXA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 102, 'SEGUROS BILBAO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 108, 'SEGUROS LAGUN ARO', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 155, 'SOMECALDE', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 210, 'SOS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 55, 'U.T.E.', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 98, 'UMAS', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 131, 'UMIVALE MATEROSS N 15', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 174, 'UROLOGIA CLINICA', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 175, 'VERTI', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 78, 'WINTERTHUR', GetDate(), 'ACT_CMBD')
INSERT INTO Addin_MDS_FinancingTypeHCDRel (MDSFinancingTypeID, InsurerID, InsurerName, LastUpdated, ModifiedBy) VALUES (7, 186, 'ZURICH', GetDate(), 'ACT_CMBD')
