delete from Addin_MDS_LeaveReason
delete from Addin_MDS_LeaveReasonHCDRel

DBCC CHECKIDENT (Addin_MDS_LeaveReason, reseed, 0)
DBCC CHECKIDENT (Addin_MDS_LeaveReasonHCDRel, reseed, 0)

insert into Addin_MDS_LeaveReason (Code,Name,Status,LastUpdated,ModifiedBy) values ('1','Domicilio: regreso residencia habitual',1,getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReason (Code,Name,Status,LastUpdated,ModifiedBy) values ('2','Traslado a otro hospital: incluye HDOM',1,getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReason (Code,Name,Status,LastUpdated,ModifiedBy) values ('3','Alta Voluntaria',1,getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReason (Code,Name,Status,LastUpdated,ModifiedBy) values ('4','Existus/Defuncion',1,getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReason (Code,Name,Status,LastUpdated,ModifiedBy) values ('5','Traslado otro centro socio-sanitario',1,getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReason (Code,Name,Status,LastUpdated,ModifiedBy) values ('6','Traslado/Ingreso mismo hospital',1,getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReason (Code,Name,Status,LastUpdated,ModifiedBy) values ('8','Otros',1,getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReason (Code,Name,Status,LastUpdated,ModifiedBy) values ('9','Desconocido',1,getDate(),'ACT_CMBD')

insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(1,313,'FACULTATIVA',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(1,870,'FACULTATIVA',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(2,314,'TRASLADO',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(2,874,'TRASLADO',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(3,312,'VOLUNTARIA',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(3,873,'VOLUNTARIA',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(4,311,'EXITUS',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(4,872,'EXITUS',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(6,871,'HOSPITALIZACION',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(8,316,'OTRO',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(8,876,'OTRA',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(8,315,'FUGA',getDate(),'ACT_CMBD')
insert into Addin_MDS_LeaveReasonHCDRel (MDSLeaveReasonID,EpisodeReasonID,EpisodeReasonName,LastUpdated,ModifiedBy)
values(8,875,'ABANDONA',getDate(),'ACT_CMBD')
