<%@ Page Language="C#" MasterPageFile="~/MasterPages/Plantilla.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="Capa_Presentacion_Pruebas_TooltipSelect_Default" Title="Untitled Page" %>
<%@ MasterType VirtualPath="~/MasterPages/Plantilla.master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="CPHB" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="CPHC" Runat="Server">
<table style="width:600px; table-layout:fixed; border-collapse:collapse;">
<colgroup>
    <col style="width:200px;" />
    <col style="width:200px;" />
    <col style="width:200px;" />
</colgroup>
<tr>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[off]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[off]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[off]"></select><br /><br /></td>
</tr>
<tr>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
</tr>
<tr>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
</tr>
<tr>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
</tr>
<tr>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
</tr>
<tr>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
</tr>
<tr>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
    <td><select class="combo" style="width:180px;" title="cssbody=[dvbdy] cssheader=[dvhdr] header=[<img src='../../../images/info.gif' style='vertical-align:middle' />  Información] body=[<label style='width:70px;'>Proyecto:</label>AAAAAAAAAAAAAAAAAAAA<br><label style='width:70px;'>Responsable:</label>BBBBBBBBBBBBBBBBBBBBBBBBB<br><label style='width:70px;'>NODO:</label>CCCCCCCCCCCCCCCCCCCCCCC<br><label style='width:70px;'>Cliente:</label>EEEEEEEEEEEEEEEEEEE] hideselects=[on]"></select><br /><br /></td>
</tr>
</table>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="CPHD" Runat="Server">
</asp:Content>

