<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:i0="http://ibWEBCORP01:102/SendPack" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SendPack" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsp:Policy wsu:Id="NetTcpBinding_ISendPack_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <msb:BinaryEncoding xmlns:msb="http://schemas.microsoft.com/ws/06/2004/mspolicy/netbinary1" />
        <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <msf:WindowsTransportSecurity xmlns:msf="http://schemas.microsoft.com/ws/2006/05/framing/policy">
                  <msf:ProtectionLevel>EncryptAndSign</msf:ProtectionLevel>
                </msf:WindowsTransportSecurity>
              </wsp:Policy>
            </sp:TransportToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256 />
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict />
              </wsp:Policy>
            </sp:Layout>
          </wsp:Policy>
        </sp:TransportBinding>
        <msf:Streamed xmlns:msf="http://schemas.microsoft.com/ws/2006/05/framing/policy" />
        <wsaw:UsingAddressing />
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:import namespace="http://ibWEBCORP01:102/SendPack" location="http://services.intranet.ibermatica/SendPack/SendPack.svc?wsdl=wsdl0" />
  <wsdl:types />
  <wsdl:binding name="NetTcpBinding_ISendPack" type="i0:ISendPack">
    <wsp:PolicyReference URI="#NetTcpBinding_ISendPack_policy" />
    <soap12:binding transport="http://schemas.microsoft.com/soap/tcp" />
    <wsdl:operation name="Saludar">
      <soap12:operation soapAction="http://ibWEBCORP01:102/SendPack/ISendPack/Saludar" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CrearPaqueteCV">
      <soap12:operation soapAction="http://ibWEBCORP01:102/SendPack/ISendPack/CrearPaqueteCV" style="document" />
      <wsdl:input name="Ficheros">
        <soap12:header message="i0:Ficheros_Headers" part="NombreFichero" use="literal" />
        <soap12:header message="i0:Ficheros_Headers" part="sXml" use="literal" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="PackExceptionFault">
        <soap12:fault use="literal" name="PackExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="CrearPaqueteIberDok">
      <soap12:operation soapAction="http://ibWEBCORP01:102/SendPack/ISendPack/CrearPaqueteIberDok" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="PackExceptionFault">
        <soap12:fault use="literal" name="PackExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="CrearPaqueteMulti">
      <soap12:operation soapAction="http://ibWEBCORP01:102/SendPack/ISendPack/CrearPaqueteMulti" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AgregarFichero">
      <soap12:operation soapAction="http://ibWEBCORP01:102/SendPack/ISendPack/AgregarFichero" style="document" />
      <wsdl:input name="Ficheros">
        <soap12:header message="i0:Ficheros_Headers" part="NombreFichero" use="literal" />
        <soap12:header message="i0:Ficheros_Headers" part="sXml" use="literal" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="PackExceptionFault">
        <soap12:fault use="literal" name="PackExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SendPack">
    <wsdl:port name="NetTcpBinding_ISendPack" binding="tns:NetTcpBinding_ISendPack">
      <soap12:address location="net.tcp://ibwebcorp01.intranet.ibermatica:103/SendPack/SendPack.svc/SendPack" />
      <wsa10:EndpointReference>
        <wsa10:Address>net.tcp://ibwebcorp01.intranet.ibermatica:103/SendPack/SendPack.svc/SendPack</wsa10:Address>
        <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
          <Spn>host/IBWEBCORP01.intranet.ibermatica</Spn>
        </Identity>
      </wsa10:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>